# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, unique=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('gender', models.CharField(choices=[('M', 'masculino'), ('F', 'feminino')], max_length=1, verbose_name='gênero')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('firstname', models.CharField(max_length=20, verbose_name='Nome')),
                ('lastname', models.CharField(max_length=20, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=18, verbose_name='Fone')),
                ('birthday', models.DateTimeField(verbose_name='Nascimento')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported', models.BooleanField(default=False, verbose_name='Importado')),
                ('outofline', models.BooleanField(default=False, verbose_name='Fora de linha')),
                ('ncm', models.CharField(max_length=8, verbose_name='NCM')),
                ('product', models.CharField(max_length=60, unique=True, verbose_name='Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='IPI')),
                ('stock', models.IntegerField(verbose_name='Estoque atual')),
                ('stock_min', models.PositiveIntegerField(default=0, verbose_name='Estoque mínimo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Brand', verbose_name='marca')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_sale', to='core.Customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='quantidade')),
                ('price_sale', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Preço de venda')),
                ('ipi_sale', models.DecimalField(decimal_places=2, default=0.1, max_digits=3, verbose_name='IPI')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_det', to='core.Product', verbose_name='produto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_det', to='core.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('gender', models.CharField(choices=[('M', 'masculino'), ('F', 'feminino')], max_length=1, verbose_name='gênero')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('firstname', models.CharField(max_length=20, verbose_name='Nome')),
                ('lastname', models.CharField(max_length=20, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=18, verbose_name='Fone')),
                ('birthday', models.DateTimeField(verbose_name='Nascimento')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('internal', models.BooleanField(default=True, verbose_name='interno')),
                ('commissioned', models.BooleanField(default=True, verbose_name='comissionado')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, default=0.01, max_digits=6, verbose_name='comissão')),
            ],
            options={
                'verbose_name': 'vendedor',
                'verbose_name_plural': 'vendedores',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_sale', to='core.Seller', verbose_name='vendedor'),
        ),
    ]
