# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-08 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161225_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Id')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(max_length=100, unique=True, verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='categoria'),
        ),
    ]
